spring:
  application:
    name: l9g-webapp-smartcard-front
  profiles:
    active: default
  config:
    import: optional:file:config.yaml

  messages:
    basename: messages
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          app:
            client-id: kasse
            client-secret: "*** not set ***"
            scope: openid,profile,email,roles
        provider:
          app:
            issuer-uri: https://id.dev.sonia.de/realms/sonia
            user-name-attribute: preferred_username

  sql:
    init:
      mode: NEVER

  datasource:
    url: "jdbc:postgresql://localhost:15432/soniapos?currentSchema=public&serverTimezone=UTC"
    username: soniapos
    password: "*** unset ***"
      
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "server"
            password: "*** unset ***"
          keystore:
            location: "file:server.p12"
            password: "*** unset ***"
            type: "PKCS12"

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: INFO
    com.zaxxer.hikari.pool.HikariPool: ERROR
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    l9g.webapp.smartcardfront.controller: DEBUG
server:
  port: 8443
  servlet:
    context-path: /
    session:
      timeout: 9h
  ssl:
    bundle: "web-server"

      
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: info,health,metrics

app:
  development: false
  api:
    base-url: http://kasse.dev.sonia.de:8080
  web:
    base-url: https://kasse.dev.sonia.de
  oauth2:
    registration-id: app
    client-id: kasse
  resource-access-roles: kasse
  account-cache:
    expire-after-write: 15
  administrator:
    usernames: "*** unset ***"
  default:
    locale: en
  barcode:
    enabled: true
    attribute-name: soniaChipcardBarcode
    image-type: png
    width: 500
    height: 80
  customer-number:
    enabled: true
    attribute-name: soniaCustomerNumber
  userid:
    attribute-name: soniaExternalUid

attributes-map:
  employeeType:
    ldap-attribute-name: employeeType
    mappingList:
      - m,Mitarb.
      - p,Prof.
      - s,Stud.
      - lb,Lehrb.
      - az,Azubi
      - em,ExtMitarb.
  department:
    ldap-attribute-name: ou
    mappingList:
      - ze,Zentrale Einrichtung
      - zs,Zentrale Serviceeinrichtung
      - rz,Rechenzentrum
      - bibl,Bibliothek
      - e,Elektrotechnik
      - i,Informatik
      - m,Maschinenbau
      - s,Soziale-Arbeit
      - h,Handel- und Sozialearbeit
      - elektrotechnik,Elektro- und Informationstechnik
      - informatik,Informatik
      - soziale-arbeit,Soziale Arbeit
      - maschinenbau,Maschinenbau
      - fahrzeugtechnik,Fahrzeugtechnik
      - gesundheitswesen,Gesundheitswesen
      - wirtschaft,Wirtschaft
      - versorgungstechnik,Versorgungstechnik
      - karl-scharfenberg,Verkehr-Sport-Tourismus-Medien
      - handel-und-soziale-arbeit,Handel und Soziale Arbeit
      - recht,Recht
